---
- name: Setup and Register Initia Validator Node
  hosts: all
  become: true
  vars_prompt:
    - name: moniker
      prompt: "Enter the moniker for the validator"
      private: no

    - name: details
      prompt: "Enter details for the validator"
      private: no

    - name: website
      prompt: "Enter the website for the validator"
      private: no

  tasks:
    - name: Retrieve PUBLIC_KEY for validator
      shell: initiad tendermint show-validator
      register: public_key
      changed_when: false

    - name: Create validator.json configuration file
      copy:
        dest: "/root/.initia/config/validator.json"
        content: |
          {
            "pubkey": "{{ public_key.stdout }}",
            "amount": "1000000uinitia",
            "moniker": "{{ moniker }}",
            "website": "{{ website }}",
            "details": "{{ details }}",
            "commission-rate": "0.10",
            "commission-max-rate": "0.20",
            "commission-max-change-rate": "0.01",
            "min-self-delegation": "1"
          }
        mode: 0644

    - name: Register the validator node
      shell: |
        initiad tx staking create-validator /root/.initia/config/validator.json \
        --chain-id="initia-1" \
        --gas="auto" \
        --gas-adjustment="1.5" \
        --gas-prices="0.025uinitia" \
        --from=wallet \
        --yes \
        --keyring-backend test
      register: validator_registration
      failed_when: "'failed' in validator_registration.stderr"
      changed_when: true

    - name: Display validator registration output
      debug:
        var: validator_registration.stdout_lines

    - name: Get the validator address
      shell: initiad keys show wallet -a --bech val --keyring-backend test
      register: validator_address
      changed_when: false

    - name: Display the validator address
      debug:
        msg: "The validator address is: {{ validator_address.stdout }}"
